---
title: "Simulating landscape-scale floral resource dynamics with floralcurves"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette1}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
#devtools::load_all()
library(floralcurves)
library(ggplot2)
```

# Generate landscape
```{r}
land1 <- landgen(area = 10000, 
                  prop1 = 0.5, 
                  prop2 = 0.1, 
                  n1 = 25, 
                  n2 = 25)
raster::plot(land1)
```

# Tabulate landscape and add flowers
```{r}
land1_tab <- landtab(land1, 
                     comp0 = c("Cirsium vulgare", "Trifolium repens", "Taraxacum agg."),
                     comp1 = c("Brassica napus"),
                     comp2 = c("Acer pseudoplatanus", "Crataegus monogyna", "Salix cinerea"),
                     prob0 = c(1, 1, 1),
                     prob1 = c(1),
                     prob2 = c(1, 1, 1),
                     traitTab = baude_traits,
                     plantNames = "name.latin")
```

# Apply phenology
```{r}
land1_pheno <- landpheno(land1_tab) 
```

# Tally sugar availability
```{r}
land1_tally_agg <- landtally(land1_pheno)

land1_tally_class <- landtally(land1_pheno, class)

land1_tally_plant <- landtally(land1_pheno, plant)

land1_tally_morph <- landtally(land1_pheno, flower.shape)
```

# Plot sugar availability
```{r}
ggplot(land1_tally_agg, aes(date, total.sugar)) +
  geom_area() +
  theme_light() +
  scale_x_date(date_labels = "%b")

ggplot(land1_tally_class, aes(date, total.sugar, fill = class)) +
  geom_area() +
  theme_light() +
  scale_x_date(date_labels = "%b")

ggplot(land1_tally_plant, aes(date, total.sugar, fill = plant)) +
  geom_area() +
  theme_light() +
  scale_x_date(date_labels = "%b")

ggplot(land1_tally_morph, aes(date, total.sugar, fill = flower.shape)) +
  geom_area() +
  theme_light() +
  scale_x_date(date_labels = "%b")
```
