---
title: "Comparing hay meadow and oilseed rape"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette2}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(floralcurves)
library(ggplot2)
# library(raster)

# baude_traits <- readr::read_csv("../inst/extdata/baude_ST11.csv") %>%
#   dplyr::mutate(bloom.start = lubridate::yday(lubridate::mdy(bloom.start)),
#                 bloom.end = lubridate::yday(lubridate::mdy(bloom.end)),
#                 bloom.peak = lubridate::yday(lubridate::mdy(bloom.peak))) %>%
#   dplyr::select(-flower.density.mean) %>%
#   dplyr::filter(!is.na(flower.density.peak)) %>%
#   dplyr::filter(!is.na(sugar.per.flower)) %>%
# 
#   # Add a class with zero floral resources; this can represent impervious surface, water, turfgrass, etc.
#   tibble::add_row(name.latin = "null", name.common = "null", family = "null",
#                   breeding.system = "null", life.span = "null", dicliny = "null",
#                   height = "null", bloom.start = 1, bloom.end = 365, bloom.peak = 180,
#                   bloom.days = 365, flower.density.peak = 0, sugar.per.flower = 0)
# 
# use_data(
#   baude_traits,
#   internal = FALSE,
#   overwrite = FALSE,
#   compress = "bzip2",
#   version = 2
# )
```

# Generate landscape
```{r}
landscape00 <- landgen(prop1 = 0.3, prop2 = 0.01, n1 = 10, n2 = 10)

raster::plot(landscape00)
```

# Tabulate landscape and add flowers
```{r}
meadow_tab <- landtab(landscape00, 
                   
                   # Hay meadow
                   comp0 = c("Trifolium pratense", "Trifolium repens", "Vicia sativa"),
                   
                   # Forest
                   comp1 = c("Acer pseudoplatanus", "Crataegus monogyna", "Salix cinerea"),
                   
                   # Developed
                   comp2 = "null",
                   
                   prob0 = c(1, 1, 1),
                   prob1 = c(0.8, 0.1, 0.1),
                   prob2 = c(1),
                   traitTab = baude_traits,
                   plantNames = "name.latin")

osr_tab <- landtab(landscape00, 
                   
                   # OSR fields
                   comp0 = "Brassica napus",
                   
                   # Forest
                   comp1 = c("Acer pseudoplatanus", "Crataegus monogyna", "Salix cinerea"),
                   
                   # Developed
                   comp2 = "null",
                   
                   prob0 = c(1),
                   prob1 = c(0.8, 0.1, 0.1),
                   prob2 = c(1),
                   traitTab = baude_traits,
                   plantNames = "name.latin")
```

# Apply phenology
```{r}
meadow_pheno <- landpheno(meadow_tab) 

osr_pheno <- landpheno(osr_tab)
```

# Tally sugar availability
```{r}
meadow_tally_agg <- landtally(meadow_pheno) %>%
  dplyr::mutate(scenario = rep("meadow", dplyr::n()))

osr_tally_agg <- landtally(osr_pheno) %>%
  dplyr::mutate(scenario = rep("osr", dplyr::n()))

meadow_osr_tally_agg <- dplyr::bind_rows(meadow_tally_agg, osr_tally_agg)

```

# Plot sugar availability
```{r}
# We could imagine a certain level below which floral resources become limiting; in reality, this line would be a curve 
# that responds to florivore density.
ggplot(meadow_osr_tally_agg, aes(date, total.sugar, color = scenario)) +
  geom_line() +
  geom_hline(yintercept = 1e9, linetype = "dashed") +
  theme_light() +
  scale_x_date(date_labels = "%b")
```
